### ISSUE TITLE
options.debug not included in built lib

### ISSUE THREAD

**Issue by jamesplease** [JasonBoy/prefetch-image#2]
:wave: hi @JasonBoy ! I know this is a very old lib that hasn't been updated in awhile, but I wanted to drop a note here that `options.debug` was added some time ago and intended to be released as a part of v1.1.0, but the lib was not built before the version was published. So although the code includes `options.debug` it doesn't work in any published versions!

**Comment by JasonBoy** [comment]
fixed in v1.1.1, looks like webpack drop the console when build

**Comment by jamesplease** [comment]
Thank you!
